### ISSUE TITLE
Materials should use `git+https`, not `GitHub+https`

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/azure-devops-demo#6]
The spec [recommends](https://github.com/in-toto/attestation/blob/main/spec/field_types.md#ResourceURI) using [SPDX Download Location](https://spdx.github.io/spdx-spec/3-package-information/#37-package-download-location), which is of the form:

    git+https://...

Currently the code outputs `GitHub+https://...` because it uses the `Build.Repository.Provider` [predefined variable](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml) verbatim.

Instead, the code should convert to either `git`, `svn,` or `tfvc`.

**Comment by gattjoe** [comment]
Will get this done tonight. Should be a straightforward fix.
